name: build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # 4.2.1
      - uses: dtolnay/rust-toolchain@ed2356ad628626a6b3f5be6c3e0255c0454fcdb9 # stable as of 2024-10-08
      - uses: taiki-e/install-action@e29814c376696105d80cec9e9efaa98bae8e7347 # 2.44.26
        with:
          tool: just

      - run: just run-all

      - run: just run-all
        env:
          BUILD_MODE: release
